name: Deploy Cloud Custodian

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Cloud Custodian
        run: pip install c7n
      - uses: actions/checkout@v2
      - name: Run Cloud Custodian
        run: |
          docker run -it --rm \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -v $(pwd):/home/ \
            custodian/c7n:latest \
            custodian run --dryrun -s /home/ --output-dir /home/ /home/CloudCustodianList.yml